#!/usr/bin/perl -w
require 5.018;
use utf8;
use strict;
use warnings;
use integer;

our($License) = "This programm underlies the GNU GENERAL PUBLIC LICENSE 2.0 or newer";
our($ScriptName) = "gede"; # our($SCRIPTNAME) = uc($ScriptName);
                   # gede = Google-Docs based EDE
our($ScriptBuild) = "5";
our($ScriptDate) =  "2026-05-24";
our($ScriptMajor) = "0";
our($ScriptMinor) = "1";
our($ScriptSub) =   "0";
our($ScriptVersion) = $ScriptMajor . "." . $ScriptMinor . "." . $ScriptSub . "-" . $ScriptBuild;
our($Author) = "Gerhard Fessler";
our($ScriptID) = "$ScriptName $ScriptVersion, $ScriptDate, © $Author, Public Domain";
our($usage) = "Aufruf    $ScriptName [Optionen]";
our($copyright) = "This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.\n";

our($usagelong) =
"Wandelt die im Verzeichnis Begriffe2.0 (bezogen auf das Verzeichnis, in dem $ScriptName aufgerufen wurde)
liegenden, aus dem Google-Drive des Informatik-Begriffsnetzes als .docx heruntergeladenen Dateien in HTML im
Informatik-Begriffsnetz 2.0-Format um.

Speichert das Ergebnis im Unterverzeichnis web2.0 des Verzeichnisses, in dem das Skript aufgerufen wird.

Falls das Verzeichnis web2.0 bereits exisitert, wird dieses in web2.0.bak umbenannt, ansonsten angelegt.

Durch Optionen kann das Verhalten angepasst werden, z. B. weitere Ausgaben erstellt werden.

Optionen:
    -d, --details: Gib weitere Daten aus, mehrfache Angabe gibt mehr aus
    -h, --help: Gib diese Daten aus und stoppe
    -s, --keinestatistik: Gib keine statistischen Daten aus
    -V, --version: Gib Id und Skriptversion aus und stoppe
    -W: Gib keine Warnungen aus
    -?: Gib diese Daten aus und stoppe

Beispiel:   $ScriptName -d
\n"; # usagelong

use open IO => ':utf8';
use open ':std';
$| = 1; # STDOUT unbuffered

use File::DosGlob;
@ARGV = map { my @g = File::DosGlob::glob($_) if /[*?]/;
	         @g ? @g : $_; } @ARGV;

use Data::Dumper;
use File::Basename;
use File::Spec;
use Time::HiRes qw(gettimeofday);
use Term::ANSIColor;

our($false) = 0;
our($true) = 1;

our(%S) = (
     'ALT' => [],
     'BaseDir' => "", # Absoluter Pfad des Verzeichnises in dem das Skript aufgerufen wird
     'DebugBuffer' => [],
     'docx' => [],
     'exitvalue' => 0,
     'Extensionen' => [],
     'html' => [],
     'KopieVon' => [],
     'leer' => [],
     'OhneExtension' => [],
     'Systemverzeichnisse' => 0,
     'Template' => [],
     'UnixHidden' => [],
     'unerwünscht' => [],
     'unkategorisiert' => [],
     'Verzeichnis' => [],
     'WederDateiNochVerzeichnis' => [],
     'WarnBuffer' => [],
     ); # Not used states:
        # Duration
        # StartTime

our(%O) = (
    'details' => 0,
    'DumpColor' => "bright_white on_yellow",
    'DumpFilename' => "",
    #'DumpFilename' => $Scriptname . "Dump.txt",
    'DumpLimit' => 30,
    'InputDir' => "Begriffe2.0",
    'OutputDir' => "web2.0",
    'StatisticColor' => "black",
    'statistics' => $true,
    'warn' => 1,
    ); # Options

# our(@TEST) = ();
# our(%TEST) = ();


&CheckArgs();
&Init();
&CheckBaseDir();

&LiesBegriffe($O{'InputDir'});
                #&DumpHash(\%O,"\nO:"); &DumpHash(\%S,"\nS:"); exit 7;
                #&DumpHash(\%O,"\nO:"); &Dprint("\nS:\n",Dumper(\%S)); exit 7;

# &ProcessUserPackageFile($UserPackageFileName);
                #&DumpArray(\@UserPackages,"\nUserPackages"); # exit 7;
                #&Dprint("\nS:\n",Dumper(\%S)); # exit 7;
# &ProcessUserPackages();
                #&DumpArray(\@Packages,"\nPackages"); # exit 7;
                #&DumpHash(\%EntryKinds,"\nEntryKinds:"); # exit 7;
# &WriteResults();

&PrintWarnsDebugs();
&PrintStatistics();
&Exit(0);

#################################################################################################

sub Init()
  { # Usage:  &Init()
    # Initialisiert das Skript

  $S{'BaseDir'} = File::Spec->rel2abs(".","");
  return;
  } # sub Init()

sub LiesBegriffe
  { # Usage:  &LiesBegriffe($DirName);
    # Falls irgenndetwas schief geht, wird eine geeignete Fehlermeldung ausgegeben und die
    # Ausführung mit einem Fehlercode beendet.
  my($DirName) = @_;
  my($Message) = "$ScriptName: Internal error: Should never be printed";
  my($CurrentDir,$DirHandle,$Dateiname,$UpDir);
  my(@Dateinamen) = ();

  &CheckInputDir($DirName);

  if ( not chdir($DirName) ) {
    $Message = "Wechsel in das Verzeichnis $DirName nicht möglich.";
    if ( $O{'details'} > 0 ) {
      $Message .= color('reset');
      $Message .= "\n                   In $DirName sollten die Eingabedateien stehen und verarbeitet werden.";
      }
    &Error($Message);
    &Exit(1);
    }
  $CurrentDir = File::Spec->rel2abs(".","");
  if ( $O{'details'} > 3 ) { print(color("green"),"→→→ $CurrentDir",color("reset"),"\n"); }
  if ( not opendir($DirHandle,".") ) {
    $Message = "Basisverzeichnis $CurrentDir der Begriffe kann nicht geöffnet werden.";
    &Error($Message);
    &Exit(1),
    }
  @Dateinamen = readdir($DirHandle);
  if ( not closedir($DirHandle) ) {
    $Message = "Basisverzeichnis $CurrentDir der Begriffe kann nach dem Lesen der Dateinamen nicht geschlossen werden.";
    &Error($Message);
    &Exit(1),
    }
                #&DumpArray(\@Dateinamen,"\nDateinamen"); # exit 7;
  foreach $Dateiname (@Dateinamen) {
    &ProcessDateiname($CurrentDir,$Dateiname);
    } # foreach @Dateinamen

  $UpDir = File::Spec->updir();
  if ( not chdir($UpDir) ) {
    $Message = "Wechsel in das übergeordnete Verzeichnis von $CurrentDir aus nicht möglich.";
    if ( $O{'details'} > 0 ) {
      $Message .= color('reset');
      $Message .= "\n                   Im übergeordneten Verzeichnis sollten im Unterverzeichnis web2.0 die Ergebnisse erstellt werden.";
      }
    &Error($Message);
    &Exit(1);
    }
  $CurrentDir = File::Spec->rel2abs(".","");
  if ( $O{'details'} > 3 ) { print(color("magenta"),"←←← $CurrentDir",color("reset"),"\n"); }
  return;
  } # sub LiesBegriffe()
 
sub ProcessDateiname
  { # Usage:  &ProcessDateiname($CurrentDir,$Dateiname);
    # Startpunkt und Teil der rekursiven Verarbeitung der Dateihierarchie
  my($CurrentDir,$Dateiname) = @_;
  my($Kategorie);

  $Kategorie = &KategorisiereDateiname($Dateiname);
                #&Dprint("$Dateiname: $Kategorie"); # exit 7;

  if ( $Kategorie eq "Systemverzeichnis" ) {
    $S{'Systemverzeichnisse'} += 1;
    return;
    } # Systemverzeichnis

  if ( $Kategorie eq "ALT" ) {
    push(@{$S{'ALT'}},$Dateiname);
    return;
    } # ALT

  if ( $Kategorie eq "Template" ) {
    push(@{$S{'Template'}},$Dateiname);
    return;
    } # Template

  if ( $Kategorie eq "KopieVon" ) {
    push(@{$S{'KopieVon'}},$Dateiname);
    return;
    } # ALT

  if ( $Kategorie eq "WederDateiNochVerzeichnis" ) {
    push(@{$S{'WederDateiNochVerzeichnis'}},$Dateiname);
    return;
    } # WederDateiNochVerzeichnis

  if ( $Kategorie eq "Verzeichnis" ) {
    push(@{$S{'Verzeichnis'}},$Dateiname);
    &ProcessVerzeichnisname($Dateiname);
    return;
    } # Verzeichnis

  if ( $Kategorie eq "leer" ) {
    push(@{$S{'leer'}},$Dateiname);
    return;
    } # leer

  if ( $Kategorie eq "UnixHidden" ) {
    push(@{$S{'UnixHidden'}},$Dateiname);
    return;
    } # UnixHidden

  if ( $Kategorie eq "OhneExtension" ) {
    push(@{$S{'OhneExtension'}},$Dateiname);
    return;
    } # OhneExtension

  if ( $Kategorie eq "unerwünscht" ) {
    push(@{$S{'unerwünscht'}},$Dateiname);
    return;
    } # Template

  if ( $Kategorie eq "html" ) {
    push(@{$S{'html'}},$Dateiname);
    return;
    } # html

  if ( $Kategorie eq "docx" ) {
    push(@{$S{'docx'}},$Dateiname);
    &ProcessDocx($Dateiname);
    return;
    } # docx

  if ( $Kategorie eq "unkategorisiert" ) {
    push(@{$S{'unkategorisiert'}},$Dateiname);
    return;
    } # Template
                &Dprint("$Dateiname: $Kategorie"); # exit 7;
  return;
  } # sub ProcessDateiname

sub ProcessVerzeichnisname
  { # Usage:  &ProcessVerzeichnisname($DirName);
    # Liest die Dateinamen im Unterverzeichnis $DirName ein und ruft für jeden Dateinamen
    # &ProcessDateiname auf
    # Teil der rekursiven Verarbeitung der Dateihierarchie
  my($DirName) = @_;
  my($Message) = "$ScriptName: Internal error: Should never be printed";
  my($DirHandle,$CurrentDir,$Dateiname,$UpDir,$PerlErrorMessage);
  my(@Dateinamen) = ();

  if ( not chdir($DirName) ) {
    $PerlErrorMessage = $!;
    $Message = "Wechsel in das Unterverzeichnis $DirName nicht möglich.";
    if ( $O{'details'} > 0 ) {
      $Message .= color('reset');
      $Message .= "\n                   In $DirName sollten Eingabedateien stehen und verarbeitet werden.";
      if ( $O{'details'} > 2 ) {
        $Message .= "\n                       Perl-Error-Message: $PerlErrorMessage";
        } 
      }
    &Error($Message);
    &Exit(1);
    }
  $CurrentDir = File::Spec->rel2abs(".","");
  if ( $O{'details'} > 3 ) { print(color("green"),"→→→",color("reset")," $CurrentDir\n"); }
  if ( not opendir($DirHandle,".") ) {
    $Message = "Unterverzeichnis $CurrentDir kann nicht geöffnet werden.";
    &Error($Message);
    &Exit(1),
    }
  @Dateinamen = readdir($DirHandle);
  if ( not closedir($DirHandle) ) {
    $Message = "Unterverzeichnis $CurrentDir kann nach dem Lesen der Dateinamen nicht geschlossen werden.";
    &Error($Message);
    &Exit(1),
    }
                #&DumpArray(\@Dateinamen,"\nDateinamen");  exit 7;
  foreach $Dateiname (@Dateinamen) {
    &ProcessDateiname($CurrentDir,$Dateiname);
    } # foreach @Dateinamen

  $UpDir = File::Spec->updir();
  if ( not chdir($UpDir) ) {
    $Message = "Wechsel in das übergeordnete Verzeichnis von $CurrentDir nicht möglich.";
    &Error($Message);
    &Exit(1);
    }
  $CurrentDir = File::Spec->rel2abs(".","");
  if ( $O{'details'} > 3 ) { print(color("magenta"),"←←←",color("reset")," $CurrentDir\n"); }
  return;
  }  # sub ProcessVerzeichnisname

sub ProcessDocx
  { # Usage:  &ProcessDocx($Dateiname);
  my($Dateiname) = @_;
                #&Dprint("ProcessDocx: $Dateiname"); # exit 7;

  return "";
  } # sub ProcessDocx

############ INPUT #### INPUT #### INPUT #### INPUT #### INPUT #### INPUT #### INPUT ############

sub CheckBaseDir
  { # Usage:  &CheckBaseDir();
    # Prüft ob das Basisverzeichnis $S{'BaseDir'} die erforderlichen Berechtigungen hat
    # Falls irgenndetwas nicht so ist, wie es sein soll, wird eine geeignete Fehlermeldung ausgegeben und die
    # Ausführung mit einem Fehlercode beendet.
  my($DirName) = $S{'BaseDir'};
  my($Message) = "$ScriptName: Internal error: Should never be printed";

  if ( not -e $DirName ) { # Seltsam: Aufrufverzeichnis soll nicht existieren
    $Message = "Aufrufverzeichnis $DirName existiert gemäß Betriebssystemabfrage nicht.";
    if ( $O{'details'} > 1 ) {
      $Message .= color('reset');
      $Message .= "\n         Maßnahme: Analysieren, was im Skript falsch läuft.";
      }
    if ( $O{'details'} > 2 ) {
      $Message .= "\n      Erläuterung: Dieser Fehler sollte nie vorkommen.";
      $Message .= "\n                   Falls doch, ist etwas Grundlegendes schief gegangen.";
      }
    &Error($Message);
    &Exit(1);
    } #  Seltsam: Aufrufverzeichnis soll nicht existieren

  if ( not -d $DirName ) { # Seltsam: Aufrufverzeichnis soll kein Verzeichnis sein
    $Message = "Aufrufverzeichnis $DirName ist gemäß Betriebssystemabfrage kein Verzeichnis.";
    if ( $O{'details'} > 1 ) {
      $Message .= color('reset');
      $Message .= "\n         Maßnahme: Analysieren, was im Skript falsch läuft.";
      }
    if ( $O{'details'} > 2 ) {
      $Message .= "\n      Erläuterung: Dieser Fehler sollte nie vorkommen.";
      $Message .= "\n                   Falls doch, ist etwas Grundlegendes schief gegangen.";
      }
    &Error($Message);
    &Exit(1);
    } #  Seltsam: Aufrufverzeichnis soll kein Verzeichnis sein

  if ( not -r $DirName ) { # Seltsam: Aufrufverzeichnis soll nicht lesbar sein
    $Message = "Aufrufverzeichnis $DirName ist gemäß Betriebssystemabfrage nicht lesbar.";
    if ( $O{'details'} > 1 ) {
      $Message .= color('reset');
      $Message .= "\n         Maßnahme: Analysieren, was im Skript falsch läuft.";
      }
    if ( $O{'details'} > 2 ) {
      $Message .= "\n      Erläuterung: Dieser Fehler sollte nie vorkommen.";
      $Message .= "\n                   Falls doch, ist etwas Grundlegendes schief gegangen.";
      }
    &Error($Message);
    &Exit(1);
    } #  Seltsam: Aufrufverzeichnis soll nicht lesbar sein

  if ( not -w $DirName ) { # Aufrufverzeichnis nicht beschreibbar
    $Message = "Aufrufverzeichnis $DirName nicht beschreibbar.";
    if ( $O{'details'} > 0 ) {
      $Message .= color('reset');
      $Message .= "\n                   In $DirName müssen Hilfs- und Ergebnisdateien geschrieben werden können.";
      }
    if ( $O{'details'} > 1 ) {
      $Message .= "\n         Maßnahme: Schreibrechte für $DirName erteilen.";
      }
    if ( $O{'details'} > 2 ) {
      $Message .= "\n      Erläuterung: Für die Erstellung der HTML-Dateien müssen die von Google Docs erstellten";
      $Message .= "\n                   .docx-Dateien im Verzeichnis $DirName mit Pandoc in ein einfach";
      $Message .= "\n                   verarbeitbares Format umgewandelt und gespeichert werden und es werden die";
      $Message .= "\n                   erzeugten HTML-Dateien usw. in das Unterverzeichnis $O{'OutputDir'} geschrieben.";
      $Message .= "\n                   Dazu muss in das Verzeichnis $DirName geschrieben werden können.";
      }
    &Error($Message);
    &Exit(1);
    } #  Aufrufverzeichnis nicht beschreibbar

  if ( not -x $DirName ) { # Aufrufverzeichnis nicht durchsuchbar
    $Message = "Dateinamen im Aufrufverzeichnis $DirName nicht ermittelbar.";
    if ( $O{'details'} > 0 ) {
      $Message .= color('reset');
      $Message .= "\n                   Die Dateinamen in $DirName müssen ermittelbar sine, damit diese";
      $Message .= "\n                   verarbeitet werden können.";
      }
    if ( $O{'details'} > 1 ) {
      $Message .= "\n         Maßnahme: Suchrechte (Unix usw: x) für $DirName erteilen.";
      }
    if ( $O{'details'} > 2 ) {
      $Message .= "\n      Erläuterung: Für die Erstellung der HTML-Dateien müssen die von Google Docs erstellten";
      $Message .= "\n                   .docx-Dateien im Aufrufverzeichnis $DirName mit Pandoc in ein einfach";
      $Message .= "\n                   verarbeitbares Format umgewandelt und gespeichert werden und es müssen";
      $Message .= "\n                   die Ergebnisse in das Unterverzeichnis $O{'OutputDir'} gespeichert werden.";
      $Message .= "\n                   Dazu sollte der Inhalt des von $DirName ermittelt werden können.";
      }
    &Error($Message);
    &Exit(1);
    } #  Aufrufverzeichnis nicht durchsuchbar

  return;
  } # CheckBaseDir

sub CheckInputDir
  { # Usage:  &CheckInputDir($DirName);
    # Prüft, ob $DirName ein les-, schreib und scanbares Verzeichnis im aktuellen Arbeitsverzeichnis ist.
    # Falls irgenndetwas nicht so ist, wie es sein soll, wird eine geeignete Fehlermeldung ausgegeben und die
    # Ausführung mit einem Fehlercode beendet.
  my($DirName) = @_;
  my($CurrentDir) = File::Spec->rel2abs(".","");
  my($Message) = "Internal error: Should never be printed";
                #&Dprint("\nCurrentDir: ",$CurrentDir); # exit 7;

  if ( not -e $DirName ) { # Verzeichnisname im aktuellen Verzeichnis nicht gefunden
    $Message = "Verzeichnis $DirName in $CurrentDir nicht gefunden.";
    if ( $O{'details'} > 0 ) {
      $Message .= color('reset');
      $Message .= "\n                   $DirName soll aus Google Docs heruntergeladene Begriffe enthalten.";
      }
    if ( $O{'details'} > 1 ) {
      $Message .= "\n    Herunterladen: In Google Docs: Rechtsklick auf Verzeichnisnamen $DirName, die";
      $Message .= "\n                   errstellte .zip-Datei im Verzeichnis $S{'BaseDir'} speichern und mit einem";
      $Message .= "\n                   zip-Programm auspacken.";
      $Message .= "\n                   Danach prüfen, ob das Verzeichnis $DirName in $S{'BaseDir'} erstellt wurde und die";
      $Message .= "\n                   Begriffe aus Google Docs als .docx-Dateien enthält, auch in";
      $Message .= "\n                   Unterverzeichnissen.";
      }
    &Error($Message);
    &Exit(1);
    } #  Verzeichnisnamen im aktuellen Verzeichnis nicht gefunden

  if ( not -d $DirName ) { # Dateinamen vorhanden, ist aber unerwarteterweise kein Verzeichnis
    $Message = "Dateiname $DirName ist in $CurrentDir vorhanden, aber kein Verzeichnis.";
    if ( $CurrentDir eq $S{'BaseDir'} ) { # In BaseDir 
      if ( $O{'details'} > 0 ) {
        $Message .= color('reset');
        $Message .= "\n                   $DirName soll ein Verzeichnis sein, das aus Google Docs";
        $Message .= "\n                   heruntergeladene Begriffe enthält.";
        }
      if ( $O{'details'} > 1 ) {
        $Message .= "\n    Maßnahmen:     $DirName umbennen, Begriffe aus Google Docs herunterladen und auspacken.";
        }
      if ( $O{'details'} > 2 ) {
        $Message .= "\n    Herunterladen: In Google Docs: Rechtsklick auf Verzeichnisnamen $DirName, die";
        $Message .= "\n                   erstellte .zip-Datei im Verzeichnis $S{'BaseDir'} speichern und mit einem";
        $Message .= "\n                   zip-Programm auspacken.";
        $Message .= "\n                   Danach prüfen, ob das Verzeichnis $DirName erstellt wurde und die";
        $Message .= "\n                   Begriffe aus Google Docs als .docx-Dateien enthält, eventuell auch in";
        $Message .= "\n                   Unterverzeichnissen.";
        }
      } # In BaseDir
    else { # In Unterverzeichnis
      if ( $O{'details'} > 1 ) {
        $Message .= "\n    Maßnahmen:     Prüfen, ob der Download der Google Docs-Dateien sich anders verhält.";
        $Message .= "\n                   Verzeichnis $O{'InputDir'} in $S{'BaseDir'} löschen und von Google Docs";
        $Message .= "\n                   neu herunterladen.";
        $Message .= "\n                   Falls das nicht hilft, ist eine detaillierte Fehleranalyse erforderlich.";
        }
      if ( $O{'details'} > 2 ) {
        $Message .= "\n    Herunterladen: In Google Docs: Rechtsklick auf Verzeichnisnamen $DirName, die";
        $Message .= "\n                   erstellte .zip-Datei im Verzeichnis $S{'BaseDir'} speichern und mit einem";
        $Message .= "\n                   zip-Programm auspacken.";
        $Message .= "\n                   Danach prüfen, ob das Verzeichnis $DirName erstellt wurde und die";
        $Message .= "\n                   Begriffe aus Google Docs als .docx-Dateien enthält, auch in";
        $Message .= "\n                   Unterverzeichnissen.";
        }
      } # In Unterverzeichnis
    &Error($Message);
    &Exit(1);
    } #  Dateinamen vorhanden, ist aber unerwarteterweise kein Verzeichnis

  if ( not -r $DirName ) { # Eingabeverzeichnisnamen gefunden: nicht lesbar
    $Message = "Dateiname $DirName in $CurrentDir nicht lesbar.";
    if ( $O{'details'} > 0 ) {
      $Message .= color('reset');
      $Message .= "\n                   $DirName sollte ein lesbares Verzeichnis in $CurrentDir sein, das aus";
      $Message .= "\n                   Google Docs heruntergeladene Begriffe enthält.";
      }
    if ( $O{'details'} > 1 ) {
      $Message .= "\n         Maßnahme: Leserechte für $DirName erteilen.";
      }
    &Error($Message);
    &Exit(1);
    } #  Eingabeverzeichnisnamen gefunden: nicht lesbar

  if ( not -w $DirName ) { # Eingabeverzeichnisnamen gefunden: nicht beschreibbar
    $Message = "Dateiname $DirName in $CurrentDir' nicht beschreibbar.";
    if ( $O{'details'} > 0 ) {
      $Message .= color('reset');
      $Message .= "\n                   In $DirName müssen Hilfsdateien geschrieben werden können.";
      }
    if ( $O{'details'} > 1 ) {
      $Message .= "\n         Maßnahme: Schreibrechte für $DirName erteilen.";
      }
    if ( $O{'details'} > 2 ) {
      $Message .= "\n      Erläuterung: Für die Erstellung der HTML-Dateien müssen die von Google Docs erstellten";
      $Message .= "\n                   .docx-Dateien im Verzeichnis $DirName mit Pandoc in ein einfach";
      $Message .= "\n                   verarbeitbares Format umgewandelt und gespeichert werden.";
      $Message .= "\n                   Dazu muss in das Verzeichnis $DirName geschrieben werden können.";
      }
    &Error($Message);
    &Exit(1);
    } #  Eingabeverzeichnisnamen gefunden: nicht beschreibbar

  if ( not -x $DirName ) { # Eingabeverzeichnisnamen gefunden: nicht scanbar
    $Message = "Dateinamen im Verzeichnis $DirName in $CurrentDir' nicht ermittelbar.";
    if ( $O{'details'} > 0 ) {
      $Message .= color('reset');
      $Message .= "\n                   Die Dateinamen in $DirName müssen ermittelbar sein, damit diese";
      $Message .= "\n                   verarbeitet werden können.";
      }
    if ( $O{'details'} > 1 ) {
      $Message .= "\n         Maßnahme: Suchrechte (Unix usw: x) für $DirName erteilen.";
      }
    if ( $O{'details'} > 2 ) {
      $Message .= "\n      Erläuterung: Für die Erstellung der HTML-Dateien müssen die von Google Docs erstellten";
      $Message .= "\n                   .docx-Dateien im Verzeichnis $DirName mit Pandoc in ein einfach";
      $Message .= "\n                   verarbeitbares Format umgewandelt und gespeichert werden.";
      $Message .= "\n                   Dazu sollte der Inhalt des Verzeichnisses $DirName ermittelt werden können.";
      }
    &Error($Message);
    &Exit(1);
    } #  Eingabeverzeichnisnamen gefunden: nicht scanbar

  return;
  } # CheckInputDir

sub KategorisiereDateiname
  { # Usage:  $Kategorie = &KategorisiereDateiname($Dateiname);
    # Analysiert den Dateinamen sowie die Eigenschaft der Datei und gibt den ermittelnden Wert als
    # Zeichenkette zurück.
    # Dateinamen werden syntaktisch und eingeschränkt semantisch geprüft.
  my($Dateiname) = @_;
  my($Basename,$Extension,$Message,$Nice);
  
  if ( $Dateiname eq "." ) { return "Systemverzeichnis"; }
  if ( $Dateiname eq ".." ) { return "Systemverzeichnis"; }
  if ( $Dateiname =~ /^ALT_/ ) { return "ALT"; }
  if ( $Dateiname =~ /ZZTemplate/i ) { return "Template"; }
  if ( $Dateiname =~ /^Kopie von/ ) { return "KopieVon"; }
  if ( $Dateiname =~ /^Copy of/ ) { return "KopieVon"; }
  if ( -d $Dateiname ) {
    if ( $Dateiname !~ /^[A-Za-z][_A-Za-z0-9-]*$/ ) {
      $Message = "Unerwünschte Zeichen im Verzeichnisnamen " . color("blue") . "$Dateiname" . color("reset") . "\n";
      $Nice = &nice_string($Dateiname);
      $Message .= "         Verzeichnisname escaped: »" . color("cyan") . $Nice . color("reset") . "«";
      &Warn($Message);
      }
    return "Verzeichnis";
    }
  if ( not -f $Dateiname ) { return "WederDateiNochVerzeichnis"; }
  if ( -z $Dateiname ) { return "leer"; }
  
  # Alle nicht-normale Dateien sind behandelt: Weiter kategorisieren.
  if ( $Dateiname =~ /^\./ ) { return "UnixHidden"; }
  if ( $Dateiname !~ /\./ ) { return "OhneExtension"; }
  if ( $Dateiname !~ /^(.*)\.([^.]+)$/ ) {
    $Message = "Dateiname " . color("blue") . "$Dateiname" . color("reset") . "hat nicht die Form basename.extension.\n";
    $Nice = &nice_string($Dateiname);
    $Message .= "         Dateiname escaped: »" . color("cyan") . $Nice . color("reset") . "«";
    &Warn($Message);
    }
  $Basename = $1;
  $Extension = $2;
  push(@{$S{'Extensionen'}},$Extension);
  if ( $Basename !~ /^[A-Za-z][_A-Za-z0-9-]*$/ ) {
    $Message = "Unerwünschte Zeichen im Dateinamen " . color("blue") . "$Dateiname" . color("reset") . "\n";
    $Nice = &nice_string($Dateiname);
    $Message .= "         Dateiname escaped: »" . color("cyan") . $Nice . color("reset") . "«";
    &Warn($Message);
    return "unerwünscht";
    }
                #&Dprint("Dateiname: '$Dateiname', Basename: '$Basename', Extension '$Extension'"); # exit 7;
  if ( $Extension =~ /^html$/i ) { return "html"; }
  if ( $Extension =~ /^docx$/i ) { return "docx"; }

  return "unkategorisiert";
  } # KategorisiereDateiname

sub CheckFileReadability
  { # Usage:  $result = &CheckFileReadability($filename);
    # Checks if the file with name as parameter exists,
    # is a readable regular file of nonzero size.
  my($fname) = @_;

  if ( not -e $fname ) { # doesn't exist
    &ErrorU("Datei '$fname' nicht gefunden");
    return;
    } # doesn't exist
  if ( not -f $fname ) { # no plain file
    &ErrorU("Datei '$fname' ist eine spezielle Datei");
    return;
    } # no plain file
  if ( not -r $fname ) { # not readable
    &ErrorU("Datei '$fname' ist nicht lesbar");
    return;
    } # not readable
  if ( -z $fname ) { # zero size
    &ErrorU("Datei '$fname' ist leer");
    return;
    } # zero size

  return $true;
  } # CheckFileReadability

sub ReadUTF8File
  { # Usage:   &ReadUTF8File($filename,$z_array);
  my($fname,$z_array) = @_;
  my($tt);
  my($l) = 0;

  if (not open(INUTF8,"<:utf8",$fname)) {
    &Error("Datei '$fname' konnte nicht zum Lesen geöffnet werden");
    } # open failed

  while (<INUTF8>) {
    chomp($_);
    $tt = $_;
    $l++;
    push(@$z_array,$tt);
    } # while (<INTP>)

  close(INUTF8);
  return;
  } # sub ReadUTF8File

############ OUTPUT #### OUTPUT #### OUTPUT #### OUTPUT #### OUTPUT #### OUTPUT ############

sub CheckOutFile
  { # Usage: $result = &CheckoutFile($filename);
    # Checks if the file with name as parameter is writeable.
    # Returns empty string if yes and Error-Message if not
  my($fname) = @_;
  my($Message) = "";

  if ( -e $fname ) {
    if ( -d $fname ) {
      $Message = "'$fname' ist ein Verzeichnisnamen, Namen nicht geschrieben";
      return $Message; }
    if ( not -f $fname ) {
      $Message = "'$fname' ist keine reguläre  Daten, Namen nicht geschrieben";
      return $Message; }
    if ( not -w $fname ) {
      $Message = "'$fname' existiert, kann aber nicht überschrieben werden, Namen nicht geschrieben";
      return $Message; }
    } # Filename exists
  return $Message;
  } # CheckOutFile

sub WriteNewUTF8File
  { # Usage:  $status = &WriteNewUTF8File($Filename,$z_text);
    #
    # Writes content of $z_text to file $filename and closes $filename
    # Returns success message if file was successfully written, else error message
  my($Filename,$z_text) = @_;
  my($l);
  my($Message) = "(Noch) keine Namen in '${Filename}' geschrieben";

  $l = scalar(@$z_text);

  if ( -e $Filename ) { rename($Filename,"$Filename.bak"); }
  if (not open(OUTUTF8,">:utf8",$Filename)) {
    return "$Filename konnte nicht geöffnet werden";
    }
  foreach $l (@$z_text) {
    if ( not print(OUTUTF8 "$l\n") ) {
      return "Schreibvorgang in $Filename ergab Fehler";
      }
    }
  if ( not close(OUTUTF8) ) {
    return "Fehler beim Schließen der Datei $Filename";
    }
  $Message = "$l Namen in die Datei '$Filename' geschrieben";
  return $Message;
  } # WriteNewUTF8File

sub WriteResultToFile()
  { # Usage:  $Result = &WriteResultToFile(\@Out,$Filename);
    # Prüft. ob die Datei $Filename schreibbar ist.
    # Falls ja, werden die String-Listenelemente von \Out als UTF-8
    # in die Date geschrieben
    # Der entstehende Status wird als $Result zurückgegeben.
  my($z_Out,$Filename) = @_;
  my($Result) = "Keine Namen in '${Filename}' geschrieben";

  $Result = &CheckOutFile($Filename); 
  if ( $Result ne "" ) { # Auf $Filename kann nicht geschrieben werden
    return $Result;
    }
  $Result = &WriteNewUTF8File($Filename,$z_Out);
  return $Result;
  } # WriteResultToFile

sub WriteResults()
  { # Usage:  &WriteResults()
    # Schreibt die gefundenen und sortieren Paktenamen in die passenden Dateien
  my($l);

  return;
  } # WriteResults

sub PrintStatistics
  { # Usage:  &PrintStatistics();
    # Print statistics
  my($l,$c,$r,$t,@o,$Extension,$e);
  my(%Extensionen) = ();

  return unless ( $O{'statistics'} );

  $c = color($O{'StatisticColor'});
  $r = color("reset");

  print("\n${c}Statistik:\n");

  if ( ($S{'Systemverzeichnisse'} > 0) and ($O{'details'} > 3) ) {
    print("    $S{'Systemverzeichnisse'} Systemverzeichnisse (., ..)\n");
    }

  @o = sort(@{$S{'ALT'}});
  $l = scalar(@o);
  if ( $l > 0 ) {
    print("    $l mit ALT_ beginnende Verzeichnis- bzw. Dateinamen, alle übersprungen\n");
    if ( $O{'details'} > 0 ) { print("        " . join(", ",@o) . "\n"); }
    }

  @o = sort(@{$S{'Template'}});
  $l = scalar(@o);
  if ( $l > 0 ) {
    print("    $l ignorierte Template-Dateien  (ZZTemplate…)\n");
    if ( $O{'details'} > 0 ) { print("        " . join(", ",@o) . "\n"); }
    }

  @o = sort(@{$S{'KopieVon'}});
  $l = scalar(@o);
  if ( $l > 0 ) {
    print("    $l mit »Kopie von« beginnende Verzeichnis- bzw. Dateinamen, alle übersprungen\n");
    if ( $O{'details'} > 0 ) { print("        " . join(", ",@o) . "\n"); }
    }

  @o = sort(@{$S{'WederDateiNochVerzeichnis'}});
  $l = scalar(@o);
  if ( $l > 0 ) {
    print("    $l Dateinamen die weder eine normale Datei noch ein Verzeichnis sind, alle übersprungen (Symbolische Links, …)\n");
    if ( $O{'details'} > 0 ) { print("        " . join(", ",@o) . "\n"); }
    }

  @o = sort(@{$S{'Verzeichnis'}});
  $l = scalar(@o);
  if ( $l > 0 ) {
    print("    $l Verzeichnisse\n");
    if ( $O{'details'} > 0 ) { print("        " . join(", ",@o) . "\n"); }
    }

  @o = sort(@{$S{'UnixHidden'}});
  $l = scalar(@o);
  if ( $l > 0 ) {
    print("    $l Versteckte Unix-Dateien (.…), alle übersprungen\n");
    if ( $O{'details'} > 0 ) { print("        " . join(", ",@o) . "\n"); }
    }

  @o = sort(@{$S{'leer'}});
  $l = scalar(@o);
  if ( $l > 0 ) {
    print("    $l leere Dateien, alle übersprungen\n");
    if ( $O{'details'} > 0 ) { print("        " . join(", ",@o) . "\n"); }
    }

  @o = sort(@{$S{'OhneExtension'}});
  $l = scalar(@o);
  if ( $l > 0 ) {
    print("    $l Dateinamen ohne Extension (*.*), alle übersprungen\n");
    if ( $O{'details'} > 0 ) { print("        " . join(", ",@o) . "\n"); }
    }

  foreach $Extension (@{$S{'Extensionen'}}) {
    if ( exists($Extensionen{$Extension}) ) { $Extensionen{$Extension} += 1; }
    else { $Extensionen{$Extension} = 1; }
    }
               # &DumpHash(\%Extensionen,"\nExtensionen:");
  @o = sort(keys(%Extensionen));
                #&DumpArray(\@o,"\no");
  $l = scalar(@o);
  if ( $l > 0 ) {
    print("    $l verschiedene Extensionen\n");
    if ( $O{'details'} > 0 ) {
      foreach $e (@o) { print("        $Extensionen{$e} $e\n"); }
      }
    }

  @o = sort(@{$S{'unerwünscht'}});
  $l = scalar(@o);
  if ( $l > 0 ) {
    print("    $l Dateinamen mit unerwünschten Zeichen, d. h. nicht [A-Za-z][_A-Za-z0-9-]*, alle übersprungen\n");
    if ( $O{'details'} > 0 ) { print("        " . join(", ",@o) . "\n"); }
    }

  @o = sort(@{$S{'html'}});
  $l = scalar(@o);
  if ( $l > 0 ) {
    print("    $l Dateinamen mit HTML-Extension, alle übersprungen\n");
    if ( $O{'details'} > 0 ) { print("        " . join(", ",@o) . "\n"); }
    }

  @o = sort(@{$S{'docx'}});
  $l = scalar(@o);
  if ( $l > 0 ) {
    print("    $l .docx-Dateinamen\n");
    if ( $O{'details'} > 0 ) { print("        " . join(", ",@o) . "\n"); }
    }

  @o = sort(@{$S{'unkategorisiert'}});
  $l = scalar(@o);
  if ( $l > 0 ) {
    print("    $l Dateinamen konnten nicht eingeordnet werden, alle übersprungen\n");
    if ( $O{'details'} > 0 ) { print("        " . join(", ",@o) . "\n"); }
    }

  print("$r");
  return;
  } # sub PrintStatistics

############ UTILITIES #### UTILITIES #### UTILITIES #### UTILITIES #### UTILITIES ############ 

sub CheckArgs
  { # Usage:   &CheckArgs();
  my($parameter, $Text);
  my(@Arguments) = ();

  foreach $parameter (@ARGV)
    { # Check parameters
    if ($parameter =~ /^-/) { &ProcessOption($parameter); } # Option found
    else { &Warn("$ScriptName mit unerwartetem Argument $parameter aufgerufen, Argument ignoriert"); }
    } # Check parameters

  return;
  } # sub CheckArgs

sub ProcessOption
  { # Usage:  &ProcessOption($optionstring);
    # Fetch and evaluate option(s)
  my($o) = @_;
  my(@o,$no);

  if ($o eq "--details") { $O{'details'}++; next; }
  if ($o eq "--help")    { &PrintUsage(); exit 0; }
  if ($o eq "--keinestatistik") { $O{'statistics'} = $false; next; }
  if ($o eq "--version") { &PrintScriptID(); exit 0; }
  if ($o =~ /^--/) { &Warn("Unbekannte Option '$o' im Aufrauf von $ScriptName, ignoriert"); return; }
  @o = split(//,$o);
  shift @o; # Remove leading -
  foreach $no (@o) { # Process single character options
    if ($no eq "d") { $O{'details'}++; next; }
    if ($no eq "h") { &PrintUsage(); exit 0; }
    if ($no eq "s") { $O{'statistics'} = $false; next; }
    if ($no eq "W") { $O{'warn'} = 0; next; }
    if ($no eq "V") { &PrintScriptID(); exit 0; }
    if ($no eq "?") { &PrintUsage(); exit 0; }
    &Warn("Unbekannte Option '$no' im Aufruf von $ScriptName, ignoriert");
    } # Process single letter options
  return;
  } # sub Processoption

sub PrintScriptID
  { # Usage:  &PrintScriptID();
    # Print script ID
  print("$ScriptID\n");
  return;
  } # sub PrintScriptID

sub PrintUsage
  { # Usage:  &PrintUsage();
    # Print usage message
  print("$ScriptID\n");
  print("$copyright\n");
  print("$usage\n");
  print("\n$usagelong");
  return;
  } # sub PrintUsage

sub PrintDebugs
  { # Usage:  &PrintDebugs();
    # Print strings in $S{'DebugBuffer'}
    # As a side effect empties $S{DebugBuffer'}
  my($t);  

  foreach $t (@{$S{'DebugBuffer'}}) { print(STDERR color($O{"DumpColor"}),"DEBUG  $t\n",color("reset")); } # Debug-Meldungen ausgeben, falls vorhanden
  $S{'DebugBuffer'} = [];  
  return;
  } # sub PrintDebugs

sub PrintWarns
  { # Usage:  &PrintWarns();
    # Print strings in $S{'WarnBuffer'}
    # As a side effect empties $S{WarnBuffer'}
  my($t);  

  return if ( $O{'warn'} < 1 ); # Don't print if warnings are suppressed
  foreach $t (@{$S{'WarnBuffer'}}) { print(STDERR color("bold red"),"WARNUNG",color("reset"),"  $t\n"); } # Warnings ausgeben, falls vorhanden
  return;
  } # sub PrintWarns

sub PrintWarnsDebugs
  { # Usage:  &PrintWarnsDebugs();
    # Print Debug and Warn Messages
  &PrintWarns();
  &PrintDebugs();
  return;
  } # sub PrintWarnsDebugs

sub Warn
  { # Usage:  &Warn($t1,$t2,$t3,...);
  my(@warnlist) = @_;

  push(@{$S{'WarnBuffer'}},@warnlist);
  } # sub Warn

sub Error
  { # Usage:  &Error($t1,$t2,$t3,...);
  my(@errorlist) = @_;
  my($t);

  foreach $t (@errorlist) {
    print(STDERR color("bold red"),"##### FEHLER ##### $t",color("reset"),"\n");
    }
  &Exit(1);
  } # sub Error

sub ErrorU
  { # Usage:  &ErrorU($t1,$t2,$t3,...);
  my(@errorlist) = @_;
  my($t);

  print(STDERR "\n");
  foreach $t (@errorlist) {
    print(STDERR color("bold red"),"##### FEHLER ##### $t",color("reset"),"\n");
    } 
  print(STDERR "\n$ScriptID\n");
  print(STDERR "\n$usage\n");
  print(STDERR "\n$usagelong\n");
  &Exit(1);
  } # sub ErrorU

sub Exit
  { # Usage:  &Exit($exitvalue); or &Exit();
  my($exitvalue) = @_;
  
  if ( defined($exitvalue) ) { exit($exitvalue); }
  else { exit $S{'exitvalue'}; };
  exit 255;
  } # sub Exit

############ CX #### CX #### CX #### CX #### CX ############ 

sub CurrentTime
  { # Usage:  &CurrentTime();
  my($now,$tt);
  my($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime();

  $year += 1900;
  $now = "$year";
  $mon += 1; $tt = "$mon"; $tt = "0$tt" if ($mon < 10);
  $now .= "-" . $tt;
  $tt = "$mday"; $tt = "0$tt" if ($mday < 10);
  $now .= "-" . $tt;
  $tt = "$hour"; $tt = "0$tt" if ($hour < 10);
  $now .= " " . $tt;
  $tt = "$min"; $tt = "0$tt" if ($min < 10);
  $now .= ":" . $tt;
  $tt = "$sec"; $tt = "0$tt" if ($sec < 10);
  $now .= ":" . $tt;

  return $now;
  } # sub CurrentTime
 
############ DEBUG #### DEBUG #### DEBUG #### DEBUG #### DEBUG ############ 

sub Dprint
  { # Usage: &Dprint($t,...);
  print(color($O{"DumpColor"}));
  print(@_);
  print(color("reset"),"\n");
  return;
  } # sub Dprint

sub DumpHash
  { # Usage:   &DumpHash($z_hash,$title);
  my($z_hash,$title) = @_;
  my($i,$j,$n,$m,$tt);
  my(@text) = ();

  print(color($O{"DumpColor"}));
  print("$title\n") if ( defined($title) );

  $n = scalar(keys(%$z_hash));
  $m = $n;
  $m = $O{'DumpLimit'} if ( $O{'DumpLimit'} < $m ); 
  $m--;
  $j = 0;
  foreach $i (sort(keys(%$z_hash))) {
    next if ($j > $m);
    $j++;
    $tt = $z_hash->{$i};
#    $tt = $$tt if (ref($tt));
    $tt = &nice_string($tt);
    push(@text,"$i -> $tt");
    }
  if ( $O{'DumpFilename'} ne "" ) {
    &WriteNewUTF8File($O{'DumpFilename'},\@text);
    print(" $n lines written to $O{'DumpFilename'}\n");
    } else {
    foreach $i (@text) { print("$i\n"); }
    print("  $n hash elements");
    }
  print(color("reset"),"\n");
  return ;
  } # sub DumpHash

sub DumpHashArray
  { # Usage:   &DumpHashArray($z_text,$title);
  my($z_hash,$title) = @_;
  my($i,$j,$n,$m,$tt,$z_tt);
  my(@text) = ();

  print(color($O{"DumpColor"}));
  print("$title\n") if ( defined($title) );

  $n = scalar(keys(%$z_hash));
  $m = $n;
  $m = $O{'DumpLimit'} if ( $O{'DumpLimit'} < $m ); 
  $m--;
  $j = 0;
  foreach $i (sort(keys(%$z_hash))) {
    next if ($j > $m);
    $j++;
    $z_tt = $z_hash->{$i};
    $tt = join(", ",@$z_tt);
    $tt = &nice_string($tt);
    push(@text,"$i -> [$tt]");
    }
  if ( $O{'DumpFilename'} ne "" ) {
    &WriteNewUTF8File($O{'DumpFilename'},\@text);
    print(" $n lines written to $O{'DumpFilename'}\n");
    } else {
    foreach $i (@text) { print("$i\n"); }
    print("  $n hash elements");
    }
  print(color("reset"),"\n");
  return ;
  } # sub DumpHashArray

sub DumpArray
  { # Usage:   &DumpArray($z_text,$title);
  my($z_text,$title) = @_;
  my($i,$n,$m,$tt);
  my(@text) = ();

  print(color($O{"DumpColor"}));
  print("$title\n") if ( defined($title) );

  print("\n");
  $n = scalar(@$z_text);
  $m = $n;
  $m = $O{'DumpLimit'} if ($O{'DumpLimit'} < $m); 
  $m--;
  foreach $i (0..$m) {
    $tt = $z_text->[$i];
    $tt = $$tt if (ref($tt));
    $tt = &nice_string($tt);
    push(@text,$tt);
    }
  if ( $O{'DumpFilename'} ne "" ) {
    &WriteNewUTF8File($O{'DumpFilename'},\@text);
    print(" $n lines written to $O{'DumpFilename'}\n");
    } else {
    foreach $i (@text) { print("$i\n"); }
    print("  $n lines");
    }
  print(color("reset"),"\n");
  return ;
  } # sub DumpArray

sub DumpArrayArray
  { # Usage:   &DumpArrayArray($z_text,$title);
  my($z_text,$title) = @_;
  my($i,$n,$m,$tt,$z_tt);
  my(@text) = ();

  print(color($O{"DumpColor"}));
  print("$title\n") if ( defined($title) );

  $n = scalar(@$z_text);
  $m = $n;
  $m = $O{'DumpLimit'} if ($O{'DumpLimit'} < $m); 
  $m--;
  foreach $i (0..$m) {
    $z_tt = $z_text->[$i];
    $tt = join(", ",@$z_tt);
    $tt = &nice_string($tt);
    push(@text,$tt);
    }
  if ( $O{'DumpFilename'} ne "" ) {
    &WriteNewUTF8File($O{'DumpFilename'},\@text);
    print(" $n lines written to $O{'DumpFilename'}\n");
    } else {
    foreach $i (@text) { print("$i\n"); }
    print("  $n lines");
    }
  print(color("reset"),"\n");
  return ;
  } # sub DumpArrayArray

sub nice_string {
  join("",
    map { $_ > 126 ?
      sprintf("\\x{%04X}", $_) :
      chr($_) =~ /[[:cntrl:]]/ ?
      sprintf("\\x%02X", $_) :
      chr($_)
    } unpack("U*", $_[0]));
  } # sGub nice_string
